# Generated by Django 5.1.2 on 2024-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('numero_referencia', models.CharField(max_length=40)),
                ('fecha_pub', models.DateField()),
                ('lugar_origen', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('imagen', models.FileField(upload_to='arte/')),
            ],
        ),
    ]
